### ISSUE TITLE
is verb suitable in url?

### ISSUE THREAD

**Issue by TheMasterOfMagic** [nsingla/api_generator#1]
For the api to be RESTful, maybe it's better to remove those verbs from the url?

**Comment by nsingla** [comment]
Sure I can look into it. can you please provide an example for clarity.

**Comment by nsingla** [comment]
I'm assuming you mean keep : 

- orders/1 instead of get_order/1

**Comment by nsingla** [comment]
you're absolutely correct, i've just pushed the fix

let me know if this looks good to you

**Comment by TheMasterOfMagic** [comment]
YES that's what I mean! Thanks for your in time reply
